package resources.orders;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-07-08T20:20:47.384+02:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "CustomerOrdersResource",
                  wsdlLocation = "classpath:wsdl/CustomerOrders.wsdl",
                  targetNamespace = "http://orders.resources/")
public class CustomerOrdersResource extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://orders.resources/", "CustomerOrdersResource");
    public final static QName CustomerOrdersResourcePort = new QName("http://orders.resources/", "CustomerOrdersResourcePort");
    static {
        URL url = CustomerOrdersResource.class.getClassLoader().getResource("wsdl/CustomerOrders.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CustomerOrdersResource.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/CustomerOrders.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerOrdersResource(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerOrdersResource(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerOrdersResource() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerOrdersResource(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerOrdersResource(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerOrdersResource(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerOrdersPortType
     */
    @WebEndpoint(name = "CustomerOrdersResourcePort")
    public CustomerOrdersPortType getCustomerOrdersResourcePort() {
        return super.getPort(CustomerOrdersResourcePort, CustomerOrdersPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerOrdersPortType
     */
    @WebEndpoint(name = "CustomerOrdersResourcePort")
    public CustomerOrdersPortType getCustomerOrdersResourcePort(WebServiceFeature... features) {
        return super.getPort(CustomerOrdersResourcePort, CustomerOrdersPortType.class, features);
    }

}
